export default {
    fenêtreDeuxVantaux: "Casement window 2 casements",
    choixBibliothèque: "Choose a catalogue",
    bobbyMenuiseriesPvc2019: "BOBBY - PVC WINDOWS 2019",
    choixFamille: "Choose a family",
    menuiseries: "Windows",
    choixProduit: "Choose a product",
    fenêtre2Vantaux: "Casement window 2 casements",
    configurationDuProduit: "Configure the product",
    renseignerDonnées: "Provide information necessary for the order",
    toutOuvrir: "Open all",
    toutFermer: "Close all",
    voirMonProduit: "Visualise my product",
    ajoutObservations: "Add observations",
    dimensionsEtQuantité: "Dimensions and quantity",
    dimensions: "Dimensions",
    hauteur: "Height",
    largeur: "Width",
    quantité: "Quantity",

    gammeCouleurForme: "Range, colour, format",
    typeCoteDormantHabillage: "Measurement type / Frame / Finish",
    typePose: "Type of installation",
    poseEnAppliqueIntérieur: "Placed proud",
    retourConfigurateur: "Return to the configurator",
    poseFeuillure: "Installed in a rebate",
    poseRenovation: "In existing frame",
    poseTunnel: "Installation tunnel",

    gammeCouleurForme: "Range, colour and form",
    forme: "Form",
    couleur: "Color of the window",
    blancTeintéMasse: "White bulk tinted",
    beigeTeintéMasse: "Beige bulk tinted",
    grisTeintéMasse: "Grey bulk tinted",
    blancChêneDoré: "White interior, golden oak exterior",
    chêneDoré: "Golden oak",
    grisAnthracite: "Anthracite grey RAL 7016",
    gamme: "Range",
    gammePop: "POP Range",
    gammeAdvance: "ADVANCE Range",
    dormantCintré: "Frame form : raised curve - height : 0mm",
    dormantPleinCintre: "Frame form : Full curve",
    vitrageCintreSurbaissé: "Glazing form : raised curve - height : 0mm",
    vitragePleinCintre: "Glazing shape : full curve",
    formeOuvrantCintreSurbaissé: "Casement form : raised curve - height : 0mm",
    formeOuvrantPleinCintre: "Casement form : full curve",

    typeCote: "Type of measurement",
    dimensionsTableau: "Opening dimensions",
    dimensionsFabricant: "Manufacturing dimensions",
    dormant60: "Frame for 60mm lining",
    dormant100: "Frame for 100mm lining",
    dormant120: "Frame for 120mm lining",
    dormant140: "Frame for 140mm lining",
    dormant160: "Frame for 160mm lining",
    dormant180: "Frame for 180mm lining",
    dormant200: "Frame for 200mm lining",
    appuiEtSeuil: "Base and sill",
    appuiStandard: "Standard base",
    sensOuvertureOb: "Opening side / Tilt and turn",
    sensOuverture: "Opening side",
    sensADéfinir: "To be defined",
    droiteTirant: "Hinges right pull to open",
    gaucheTirant: "Hinges left pull to open",
    oscilloBattant: "Tilt and turn",
    oscilloBattant1Vantail: "Tilt and turn 1 casement",
    aucunOscilloBattant: "No tilt and turn",


    vitragePetitBois: "Glazing / glazing bars",
    vitrage: "Glazing",
    doubleVitrage: "DOUBLE GLAZING",
    doubleVitrageVIR416WarmEdgeArgon4: "Double glazing VIR 4/16 Warm Edge + argon/4",
    doubleVitrageVIR414WarmEdgeArgon6: "Double glazing VIR 4/14 Warm Edge + argon/6",
    doubleVitrageVIR620WarmEdgeArgon6: "Double glazing VIR 6/20 Warm Edge + argon/6",

    doubleVitrageAutoNettoyant: "SELF-CLEANING DOUBLE GLAZING",
    doubleVitrageVIR416WarmEdgeArgon4Autonettoyant: "Double glazing VIR 4/16 Warm Edge + argon/4 autonettoyant",
    doubleVitrageVIR414WarmEdgeArgon6Autonettoyant: "Double glazing VIR 4/14 Warm Edge + argon/6 autonettoyant",
    doubleVitrageVIR44214WarmEdgeArgon442Autonettoyant: "Double glazing VIR 44.2/14 Warm Edge + argon/44.2 autonettoyant",

    doubleVitrageAcoustique: "ACOUSTIC DOUBLE GLAZING",
    doubleVitrageAcoustiqueVIR420WarmEdgeArgon8: "Acoustic double glazing: VIR 4/20 Warm Edge + argon/8",
    doubleVitrageAcoustiqueVIR1014WarmEdgeArgon441silence: "Acoustic double glazing: VIR 10/14 Warm Edge + argon/44.1 silence",

    doubleVitrageSecurité: "HIGH-SECURITY DOUBLE GLAZING",
    doubleVitrageScuritVIR418WarmEdgeArgon442: "Security double glazing: VIR 4/18 Warm Edge + argon/44.2",
    doubleVitrageScuritVIR44218WarmEdgeArgon4: "Security double glazing: VIR 44.2/18 Warm Edge + argon/4",
    doubleVitrageScuritVIR44214WarmEdgeArgon442: "Security double glazing: VIR 44.2/14 Warm Edge + argon/44.2",


    remplissagePlein: "PANELS",
    panneauMousseDe24mm: "Foam panel 24mm",
    panneauRainuréDe31mm: "Grooved panel 31mm",

    petitBois: "Type glazing bars",
    aucun: "None",
    petitsBoisIncorporsMonocoloreBlanc901626x8: "Integrated glazing bars, white 9016 26 x 8",
    petitsBoisIncorporsMonocoloreRAL26x8: "Integrated glazing bars single colour RAL 26 x 8",
    petitsBoisIncorporsBlancIntrieuretRALExtrieur26x8: "Integrated glazing bars white inside RAL outside 26 x 8",
    petitsBoisIncorporsLaiton10x8: "Integrated glazing bars, brass 10 x 8",
    PetitsBoisIncorporsTitane10x8: "Integrated glazing bars, titanium 10 x 8",
    petitsBoisRapportsDe45mm: "Mortised glazing bars de 45 mm",
    petitsBoisRapportsDe26mm: "Mortised glazing bars de 26 mm",


    prixTarif: "Catalogue price",
    prixDeVente: "Sale price",
    prixDAchat: "Purchase",
    remise: "Reduction",
    vente: "Sale",
    coefficient: "Markup",

    remiseClient: "Client rebate",
    remiseUnitaire: "Unit reduction",
    remisePct: "% reduction",
    prixDeVenteClient: "Client sale price",

    margeVendeur: "Seller's margin",
    unitaire: "Unitary",
    globale: "Overall",
    taux: "Rate",
    totalHT: "Total ex VAT",
    tauxTvaPct: "VAT rate (%)",
    totalTtc: "Total with VAT",

    ajouterCeProduit: "Add this product",

}