export default {
    myMessage:"hello cobber",
    choixBibliothèque:"Choose a catalogue",
    bobbyMenuiseriesPvc2019:"BOBBY - PVC WINDOWS 2019",
    choixFamille:"Choose a family",
    menuiseries:"Windows",
    choixProduit:"Choose a product",
    fenêtre2Vantaux: "Casement window 2 casements",
    configurationDuProduit:"Configure the product",
    renseignerDonnées:"Provide information necessary for the order",
    toutOuvrir:"Open all",
    toutFermer:"Close all",
    voirMonProduit:"Visualise my product",
    ajoutObservations:"Add observations",
    dimensionsEtQuantité:"Dimensions and quantity",
    dimensions:"Dimensions",
    hauteur:"Height",
    largeur:"Width",
    quantité:"Quantity",

    gammeCouleurForme:"Range, colour, format",
    typeCoteDormantHabillage: "Measurement type / Frame / Finish",
    typePose: "Type of installation",
    poseEnAppliqueIntérieur: "Placed proud",
    retourConfigurateur:"Return to the configurator",
    poseFeuillure:"Installed in a rebate",
    poseRenovation:"In existing frame",
    poseTunnel:"Installation tunnel",

    gammeCouleurForme: "Range, colour and form",
    forme: "Form",
    couleur:"Color of the window",
    blancTeintéMasse:"White bulk tinted",
    beigeTeintéMasse:"Beige bulk tinted",
    grisTeintéMasse:"Grey bulk tinted",
    blancChêneDoré:"White interior, golden oak exterior",
    chêneDoré:"Golden oak",
    grisAnthracite:"Anthracite grey RAL 7016",
    gamme:"Range",
    gammePop:"POP Range",
    gammeAdvance:"ADVANCE Range",
    dormantCintré: "Frame form : raised curve - height : {}mm",
    dormantPleinCintre: "Frame form : Full curve",
    vitrageCintreSurbaissé:"Glazing form : raised curve - height : {}mm",
    vitragePleinCintre: "Glazing shape : full curve",
    formeOuvrantCintreSurbaissé: "Casement form : raised curve - height : {}mm",
    formeOuvrantPleinCintre:"Casement form : full curve",

    typeCote:"Type of measurement",
    dimensionsTableau:"Opening dimensions",
    dimensionsFabricant:"Manufacturing dimensions",
    dormant60:"Frame for 60mm lining",
    dormant100:"Frame for 100mm lining",
    dormant120:"Frame for 120mm lining",
    dormant140:"Frame for 140mm lining",
    dormant160:"Frame for 160mm lining",
    dormant180:"Frame for 180mm lining",
    dormant200:"Frame for 200mm lining",
    appuiEtSeuil:"Base and sill",
    appuiStandard:"Standard base",
    sensOuvertureOb:"Opening side / Tilt and turn",
    sensOuverture:"Opening side",
    sensADéfinir: "To be defined",
    droiteTirant: "Hinges right pull to open",
    gaucheTirant: "Hinges left pull to open",
    oscilloBattant:"Tilt and turn",
    oscilloBattant1Vantail: "Tilt and turn 1 casement",
    aucunOscilloBattant:"No tilt and turn",
}