export default {
    myMessage: "bonjour cobber",
    choixBibliothèque: "Choix de la bibliothèque",
    bobbyMenuiseriesPvc2019: "BOBBY - MENUISERIES PVC 2019",
    choixFamille: "Choix de la famille",
    menuiseries: "Menuiseries",
    choixProduit: "Choix du produit",
    fenêtre2Vantaux: "Fenêtre 2 vantaux",
    configurationDuProduit: "Configuration du produit",
    renseignerDonnées: "Renseigner les données de commande fournisseur",
    toutOuvrir: "Tout ouvrir",
    toutFermer: "Tout fermer",
    voirMonProduit: "Voir mon produit",
    ajoutObservations: "Ajouter des observations",
    dimensionsEtQuantité: "Dimensions et quantité",
    dimensions: "Dimensions",
    hauteur: "Hauteur",
    largeur: "Largeur",
    quantité: "Quantité",

    gammeCouleurForme: "Gamme, couleur et forme",
    typeCoteDormantHabillage: "Type de côte / Dormant / Habillage",
    typePose: "Type de pose",
    poseEnAppliqueIntérieur: "Pose en applique intérieur",
    retourConfigurateur: "Retour au configurateur",
    poseFeuillure: "Pose feuillure",
    poseRenovation: "Pose rénovation",
    poseTunnel: "Pose tunnel",

    gammeCouleurForme: "Gamme, couleur et forme",
    forme: "Forme",
    couleur: "Couleur de la menuiserie",
    blancTeintéMasse: "Blanc teinté masse",
    beigeTeintéMasse: "Beige teinté masse",
    grisTeintéMasse: "Gris teinté masse",
    blancChêneDoré: "Blanc intérieur et Chêne doré extérieur",
    chêneDoré: "Chêne doré",
    grisAnthracite: "Gris anthracite RAL 7016",
    gamme: "Gamme",
    gammePop: "Gamme POP",
    gammeAdvance: "Gamme ADVANCE",
    dormantCintré: "Forme dormant: Cintre surbaissé - Flèche : {}mm",
    dormantPleinCintre: "Forme dormant : Plein cintre",
    vitrageCintreSurbaissé: "Forme vitrage : Cintre surbaissé - Flèche : {}mm",
    vitragePleinCintre: "Forme vitrage : Plein cintre",
    formeOuvrantCintreSurbaissé: "Forme ouvrant : Cintre surbaissé - Flèche : {}mm",
    formeOuvrantPleinCintre: "Forme ouvrant : Plein cintre",

    typeCote: "Type de cote",
    dimensionsTableau: "Dimensions tableau",
    dimensionsFabricant: "Dimensions fabricant",
    dormant60: "Dormant pour doublage de 60mm",
    dormant100: "Dormant pour doublage de 100mm",
    dormant120: "Dormant pour doublage de 120mm",
    dormant140: "Dormant pour doublage de 140mm",
    dormant160: "Dormant pour doublage de 160mm",
    dormant180: "Dormant pour doublage de 180mm",
    dormant200: "Dormant pour doublage de 200mm",
    appuiEtSeuil: "Appui et Seuil",
    appuiStandard: "Appui standard",
    sensOuvertureOb: "Sens ouverture / Oscillo-battant",
    sensOuverture: "Sens ouverture",
    sensADéfinir: "Sens à définir",
    droiteTirant: "Droite tirant",
    gaucheTirant: "Gauche tirant",
    oscilloBattant: "Oscillo-battant",
    oscilloBattant1Vantail: "Oscillo-battant 1 vantail",
    aucunOscilloBattant: "Sans oscillo-battant",

    vitragePetitBois: "Vitrage / Petit bois",
    vitrage: "Vitrage",
    doubleVitrage: "DOUBLE VITRAGE",
    doubleVitrageVIR416WarmEdgeArgon4: "Double vitrage VIR 4/16 Warm Edge + argon/4",
    doubleVitrageVIR414WarmEdgeArgon6: "Double vitrage VIR 4/14 Warm Edge + argon/6",
    doubleVitrageVIR620WarmEdgeArgon6: "Double vitrage VIR 6/20 Warm Edge + argon/6",

    doubleVitrageAutoNettoyant: "DOUBLE VITRAGE AUTONETTOYANT",
    doubleVitrageVIR416WarmEdgeArgon4Autonettoyant: "Double vitrage VIR 4/16 Warm Edge + argon/4 autonettoyant",
    doubleVitrageVIR414WarmEdgeArgon6Autonettoyant: "Double vitrage VIR 4/14 Warm Edge + argon/6 autonettoyant",
    doubleVitrageVIR44214WarmEdgeArgon442Autonettoyant: "Double vitrage VIR 44.2/14 Warm Edge + argon/44.2 autonettoyant",

    doubleVitrageAcoustique: "DOUBLE VITRAGE ACOUSTIQUE",
    doubleVitrageAcoustiqueVIR420WarmEdgeArgon8: "Double vitrage acoustique : VIR 4/20 Warm Edge + argon/8",
    doubleVitrageAcoustiqueVIR1014WarmEdgeArgon441silence: "Double vitrage acoustique : VIR 10/14 Warm Edge + argon/44.1 silence",

    doubleVitrageSecurité: "DOUBLE VITRAGE SECURITE",
    doubleVitrageScuritVIR418WarmEdgeArgon442: "Double vitrage sécurité : VIR 4/18 Warm Edge + argon/44.2",
    doubleVitrageScuritVIR44218WarmEdgeArgon4: "Double vitrage sécurité : VIR 44.2/18 Warm Edge + argon/4",
    doubleVitrageScuritVIR44214WarmEdgeArgon442: "Double vitrage sécurité : VIR 44.2/14 Warm Edge + argon/44.2",


    remplissagePlein: "REMPLISSAGE PLEIN",






}